name: Persistent QEMU VM with Auto-Restart

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # Every 5 hours

jobs:
  persistent-vm:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y qemu-kvm cloud-image-utils genisoimage openssh-client wget tmate

    - name: Restore persistent disk
      id: restore
      run: |
        if curl -s -f -O -L "https://github.com/${{ github.repository }}/releases/download/vm-disk/persistent.img"; then
          echo "Disk restored from release."
        else
          echo "No previous disk found, creating new one."
          qemu-img create -f qcow2 persistent.img 10G
        fi

    - name: Download Ubuntu cloud image
      run: |
        wget -q https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img -O ubuntu.img

    - name: Create cloud-init config (auto root login)
      run: |
        mkdir -p seed
        echo "instance-id: githubvm" > seed/meta-data
        cat > seed/user-data <<EOF
        #cloud-config
        users:
          - name: root
            ssh-authorized-keys:
              - $(curl -s https://api.github.com/repos/${{ github.repository_owner }}/keys | grep '"key":' | head -n1 | cut -d'"' -f4)
            sudo: ALL=(ALL) NOPASSWD:ALL
            shell: /bin/bash
        ssh_pwauth: false
        disable_root: false
        EOF
        cloud-localds seed.img seed/user-data seed/meta-data

    - name: Launch VM with restored disk
      run: |
        nohup qemu-system-x86_64 \
          -enable-kvm \
          -m 16000 -smp 4 \
          -drive file=persistent.img,format=qcow2 \
          -drive file=ubuntu.img,format=qcow2 \
          -drive file=seed.img,format=raw \
          -net nic -net user,hostfwd=tcp::2222-:22 \
          -nographic > vm.log 2>&1 &

    - name: Wait for VM SSH to be ready
      run: |
        for i in {1..30}; do
          nc -z localhost 2222 && echo "VM is up!" && break
          echo "Waiting for VM SSH..."
          sleep 3
        done

    - name: Start tmate for terminal access
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: false

    - name: Upload persistent disk for next run
      if: always()
      run: |
        curl -sL https://github.com/${{ github.repository }}/releases/download/vm-disk/persistent.img && echo "Backup already exists" && exit 0
        gh release create vm-disk persistent.img -t "VM Disk Backup" -n "Auto backup of persistent disk"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
